### ISSUE TITLE
Job rerun - Remediation plan from Preupgrade check with Leapp

### ISSUE THREAD

**Issue by stejskalleos** [oamg/foreman_leapp#40]
**Steps to reproduce**
* Run job Preupgrade check with Leapp
* After finish click on rerun
* Change job to remediation plan, add some ids and run it

**Expected results:*
Job successfully finished.

**Actual result:**
Run failed because of:
```
2020-04-06T11:55:21 [I|bac|] Task {label: Actions::RemoteExecution::RunHostJob, id: 1369564d-a7b7-4f46-b582-b8037bca3e62, execution_plan_id: 290050e6-e74f-4062-aa09-7f71ade7b2ef} state changed: stopped  result: error
2020-04-06T11:55:22 [I|bac|] Event delivered by request b399d447-f0a0-4f93-ac86-95f1c6483399
2020-04-06T11:55:22 [E|bac|] 783: unexpected token at '' (JSON::ParserError)
 | /home/lstejskal/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
 | /home/lstejskal/Projects/plugins/leapp/app/lib/actions/preupgrade_job.rb:31:in `format_output'
 | /home/lstejskal/Projects/plugins/leapp/app/lib/actions/preupgrade_job.rb:18:in `finalize'
 | /home/lstejskal/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dynflow-1.4.3/lib/dynflow/action.rb:584:in `block (2 levels) in execute_finalize'
 | /home/lstejskal/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dynflow-1.4.3/lib/dynflow/middleware/stack.rb:27:in `pass'
```

For some reason ``actions/preupgrade_job.rb`` have been planned.

**Comment by adamruzicka** [comment]
Could it be that even though you changed the template, it still "inherited" the feature from the previous job?

**Comment by stejskalleos** [comment]
Yop, that was probably that problem. Looks like https://github.com/oamg/foreman_leapp/pull/44 fixed it.
